### ISSUE TITLE
Type code TEST_MPL_O not valid for Biomass

### ISSUE THREAD

**Issue by lmar76** [stcorp/procsim#27]
We are trying to simulate the Level-0 Step3 processing. The Task execution fails with the following error message:

```
[E] Type code TEST_MPL_O not valid for Biomass
```

In attachment you can find a zip file containing:
- `wrapper.sh`: shell script simulating the Task executable (it calls the `procsim` executable according to the documentation)
- `dockerfile`: updated dockerfile needed to create one executable for each processor Task (each one is a synbolic link to the `wrapper.sh` script)
- `scenarioConf.json`: scenario configuration file
- `L0PFStep3_SM1_01_01_Step3_05_03L01_2508.zip`: working directory created by the CPF and containing the job order and the input products.

[L0Step3_failed_ProcSim1.6.zip](https://github.com/stcorp/procsim/files/8334859/L0Step3_failed_ProcSim1.6.zip)

**Comment by mivermeu** [comment]
We were able to reproduce this issue and fixed it in PR #28. MPL products are now recognized and handled properly.

Thank you for supplying a complete set of data and scripts so that we could investigate this issue. Just as a heads-up, during debugging, another error appeared relating to an unexpected deviation from the MPH format. In the MPH of product BIO_AUX_ERP____20201201T000000_20201231T235959_01_046UV2, the `eop:processingDate` is given with milliseconds where no decimals are expected.

**Comment by lmar76** [comment]
I have executed the same test with v1.6.1. The error previously detected does not occur anymore but now procsim raises an exception that seems to be related to the parsing of a date:

```
% /opt/pnode/bin/procsim -t level0_task3.sh -j BIO_L0PFStep3-SM1_01.01_2470-2474_20220323T121107_JobOrder_upd.xml scenarioConf.json 
2022-03-25T12:30:00.172704 cpf-ipf-p-1 L0PFStep3-SM1 01.01 Step3 [0000046085]: [I] Procsim v1.6.1 processor stub simulator
2022-03-25T12:30:00.172754 cpf-ipf-p-1 L0PFStep3-SM1 01.01 Step3 [0000046085]: [I] Simulate scenario L0 step 3, consolidation of Monitoring products (Measurement Mode)
2022-03-25T12:30:00.172765 cpf-ipf-p-1 L0PFStep3-SM1 01.01 Step3 [0000046085]: [I] Read JobOrder BIO_L0PFStep3-SM1_01.01_2470-2474_20220323T121107_JobOrder_upd.xml
2022-03-25T12:30:00.172773 cpf-ipf-p-1 L0PFStep3-SM1 01.01 Step3 [0000046085]: [D] JobOrder validation against schema: OK
2022-03-25T12:30:00.172780 cpf-ipf-p-1 L0PFStep3-SM1 01.01 Step3 [0000046085]: [I] Read task Step3 from the JobOrder
2022-03-25T12:30:00.172791 cpf-ipf-p-1 L0PFStep3-SM1 01.01 Step3 [0000046085]: [I] Input type AUX_PP0___: BIO_AUX_PP0____20000101T000000_20500101T000000_01_000000
2022-03-25T12:30:00.172800 cpf-ipf-p-1 L0PFStep3-SM1 01.01 Step3 [0000046085]: [I] Input type MPL_ORBPRE: BIO_TEST_MPL_ORBPRE_20210201T000000_20210202T000000_0001.EOF
2022-03-25T12:30:00.172814 cpf-ipf-p-1 L0PFStep3-SM1 01.01 Step3 [0000046085]: [I] Input type S1_RAWP_0M: BIO_S1_RAWP_0M_20210201T002432_20210201T002932_T_G___M01_C___T000_F____42_BLKCCN
2022-03-25T12:30:00.172823 cpf-ipf-p-1 L0PFStep3-SM1 01.01 Step3 [0000046085]: [I] Input type AUX_ERP___: BIO_AUX_ERP____20201201T000000_20201231T235959_01_046UV2
2022-03-25T12:30:00.185540 cpf-ipf-p-1 L0PFStep3-SM1 01.01 Step3 [0000046085]: [D] Parse BIO_S1_RAWP_0M_20210201T002432_20210201T002932_T_G___M01_C___T000_F____42_BLKCCN for S1_RAW__0M
2022-03-25T12:30:00.187433 cpf-ipf-p-1 L0PFStep3-SM1 01.01 Step3 [0000046085]: [D] Data take id 1 of BIO_AUX_PP0____20000101T000000_20500101T000000_01_000000 matches
2022-03-25T12:30:00.187977 cpf-ipf-p-1 L0PFStep3-SM1 01.01 Step3 [0000046085]: [D] Data take id 1 of BIO_S1_RAWP_0M_20210201T002432_20210201T002932_T_G___M01_C___T000_F____42_BLKCCN matches
Traceback (most recent call last):
  File "/opt/pnode/bin/procsim", line 8, in <module>
    sys.exit(main())
  File "/opt/pnode/lib/python3.9/site-packages/procsim/core/main.py", line 384, in main
    if job_task.inputs and not gen.parse_inputs(job_task.inputs):
  File "/opt/pnode/lib/python3.9/site-packages/procsim/biomass/level0_product_generator.py", line 308, in parse_inputs
    hdr.parse(mph_file_name)
  File "/opt/pnode/lib/python3.9/site-packages/procsim/biomass/main_product_header.py", line 824, in parse
    processing_date = _time_from_iso_short(processing_info.findtext(eop + 'processingDate'))
  File "/opt/pnode/lib/python3.9/site-packages/procsim/biomass/main_product_header.py", line 72, in _time_from_iso_short
    return datetime.datetime.strptime(timestr, ISO_TIME_FORMAT_SHORT)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: .567
luca mariani@ESR01104747 L0PFStep3_SM1_01_01_Step3_05_03L01_2508 % 
```
Can you please check?

**Comment by mivermeu** [comment]
Indeed, this issue came up during testing. The `eop:processingDate` is given with millisecond precision where the format we expect (from the BIO-ESA-EOPG-EEGS-TN-0051 MPH definition) is `dateTime in ISO 8601 format YYYY-MM-DDThh:mm:ssZ`. I verified that removing the decimals in this field solves the issue.

**Comment by lmar76** [comment]
@mivermeu thank you!
