### ISSUE TITLE
Global Coverage ID allowed values

### ISSUE THREAD

**Issue by lmar76** [stcorp/procsim#31]
According to the Biomass MPH Definition document v2.3, the allowed values for the `bio:globalCoverageID` parameter are: `1`, `2`, `3`, `4`, `5`, `6`, `NA`.

I tried to generate a S1_RAW__0M product (input for a processing). The configuration is the following:

```json
{
    "mission": "biomass",
    "scenarios": [
        {
            "name": "Inputs generation",
            "file_name": "N/A",
            "processor_name": "Procsim",
            "processor_version": "1.6.2",
            "task_name": "N/A",
            "task_version": "N/A",
            "log_level": "debug",
            "baseline": 1,
            "mission_phase": "INTERFEROMETRIC",
            "data_take_id": 1234,
            "global_coverage_id": "1",
            "major_cycle_id": "1",
            "repeat_cycle_id": "1",
            "track_number": "100",
            "outputs": [
                {
                    "type": "S1_RAW__0M",
                    "begin_position": "2017-04-19T10:19:39.636000Z",
                    "end_position": "2017-04-19T10:22:36.450000Z",
                    "num_l0_lines": "100",
                    "num_l0_lines_corrupt": "0",
                    "num_l0_lines_missing": "0",
                    "output_path": "workdir/inputs/S1_RAW__0M"
                }
            ]
        }
    ]
}
```

But I gt the following result:

```
% procsim -s "Inputs generation" framer-scenario-gen.json
2022-05-18T10:49:30.439100 N/A    [0000046035]: [I] Procsim v1.6.2 processor stub simulator
2022-05-18T10:49:30.439139 N/A    [0000046035]: [I] Simulate scenario Inputs generation
2022-05-18T10:49:30.439150 N/A    [0000046035]: [I] No input files
2022-05-18T10:49:30.451312 N/A    [0000046035]: [D] Set baseline to 1
2022-05-18T10:49:30.451353 N/A    [0000046035]: [D] Set mission_phase to INTERFEROMETRIC
2022-05-18T10:49:30.451365 N/A    [0000046035]: [D] Set data_take_id to 1234
2022-05-18T10:49:30.451375 N/A    [0000046035]: [D] Overwrite global_coverage_id from NA to 1
2022-05-18T10:49:30.451383 N/A    [0000046035]: [D] Overwrite major_cycle_id from 1 to 1
2022-05-18T10:49:30.451390 N/A    [0000046035]: [D] Overwrite repeat_cycle_id from __ to 1
2022-05-18T10:49:30.453876 N/A    [0000046035]: [D] Set begin_position to 2017-04-19 10:19:39.636000
2022-05-18T10:49:30.453940 N/A    [0000046035]: [D] Set end_position to 2017-04-19 10:22:36.450000
2022-05-18T10:49:30.453954 N/A    [0000046035]: [D] Set num_l0_lines to 100
2022-05-18T10:49:30.453964 N/A    [0000046035]: [D] Set num_l0_lines_corrupt to 0
2022-05-18T10:49:30.453972 N/A    [0000046035]: [D] Set num_l0_lines_missing to 0
2022-05-18T10:49:30.453983 N/A    [0000046035]: [D] Overwrite output_path from . to workdir/inputs/S1_RAW__0M
2022-05-18T10:49:30.454256 N/A    [0000046035]: [D] Output directory is /Users/luca mariani/Workspace/data/BIOMASS/From_Aresys/BiomassTDS/procsim/workdir/inputs/S1_RAW__0M
2022-05-18T10:49:30.454273 N/A    [0000046035]: [D] Use begin_position as input for validity start time
2022-05-18T10:49:30.454282 N/A    [0000046035]: [D] Use end_position as input for validity stop time
Traceback (most recent call last):
  File "/opt/pnode/bin/procsim", line 8, in <module>
    sys.exit(main())
  File "/opt/pnode/lib/python3.9/site-packages/procsim/core/main.py", line 387, in main
    gen.generate_output()
  File "/opt/pnode/lib/python3.9/site-packages/procsim/biomass/level0_product_generator.py", line 346, in generate_output
    name_gen = self._create_name_generator(self._hdr)
  File "/opt/pnode/lib/python3.9/site-packages/procsim/biomass/product_generator.py", line 119, in _create_name_generator
    name_gen.global_coverage_id = acq.global_coverage_id
  File "/opt/pnode/lib/python3.9/site-packages/procsim/biomass/product_name.py", line 122, in global_coverage_id
    self.GLOBAL_COVERAGE_IDS.index(id)  # Test
ValueError: '1' is not in list
```

Changing `"global_coverage_id": "1",` to `"global_coverage_id": "01",` the generation succeeds but the `bio:globalCoverageID` parameter in the MPH is set to `01` instead of `1`.

**Comment by pe1obw** [comment]
I assume the issue is solved by this fix!

**Comment by lmar76** [comment]
Hi Werner, the issue is fixed. I think we can leave the fix on master and include it in the next release (i.e. the L1 virtual frame). Thank you.
